[user]
name = "jiyuan"
email = "olderfe66@gmail.com"

[ui]
default-command = ["log", "-n", "10"]
editor = "nvim"
diff-formatter = ["difft", "--color=always", "$left", "$right"]

[remotes.origin]
auto-track-created-bookmarks = "glob:*"

[revsets]
log = "latest(all(), 10)"

[revset-aliases]
'closest_pushable(to)' = 'heads(::to & ~description(exact:"") & (~empty() | merges()))'

[aliases]
fetch = ["git", "fetch"]
ft = ["git", "fetch"]
push = ["git", "push"]
bsp = ["bookmark", "set", "-B", "-r", "@-"]
tug = ["bookmark", "advance", "--to", "closest_pushable(@)"]
